---
- name: Установка и настройка WordPress и MySQL
  hosts: all
  gather_facts: false
  become: true
  vars:
    mysql_root_password: "root1234"
    mysql_database: "wordpress_database"
    mysql_user: "wordpress_user"
    mysql_password: "wordpress_password"
    repl_user: "replication_user"
    repl_password: "replication_pass"
    mysql_primary_port: 3307
    mysql_replica_port: 3308
    mysql_dump_path: "/tmp/mysql_dump.sql"

  tasks:
    - name: Установка необходимых пакетов
      ansible.builtin.apt:
        name:
          - docker.io
          - python3-pip
          - python3-docker
          - python3-mysqldb
        state: present
        update_cache: true

    - name: Запущен ли Docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Создание Docker сети
      community.docker.docker_network:
        name: wp_net
        state: present

    - name: Получение образа MySQL
      community.docker.docker_image:
        name: mysql:5.7
        source: pull

    - name: Получение образа WordPress
      community.docker.docker_image:
        name: wordpress:latest
        source: pull

    # Создание и настройка мастер контейнера MySQL
    - name: Запуск мастер MySQL в контейнере
      community.docker.docker_container:
        name: mysql_primary
        image: mysql:5.7
        restart_policy: always
        state: started
        published_ports:
          - "{{ mysql_primary_port }}:3306"
        networks:
          - name: wp_net
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_DATABASE: "{{ mysql_database }}"
          MYSQL_USER: "{{ mysql_user }}"
          MYSQL_PASSWORD: "{{ mysql_password }}"
        command: >
          --server-id=1
          --log-bin=mysql-bin
          --binlog-format=ROW
          --bind-address=0.0.0.0
        volumes:
          - mysql_primary_data:/var/lib/mysql
        recreate: yes

    - name: Проверка что мастер MySQL доступен
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: "{{ mysql_primary_port }}"
        delay: 5
        timeout: 60

    - name: Ждём, пока MySQL master внутри контейнера ответит ping
      community.docker.docker_container_exec:
        container: mysql_primary
        command: mysqladmin -h127.0.0.1 --protocol=TCP -uroot -p{{ mysql_root_password }} ping
      register: ping
      retries: 10
      delay: 3
      until: ping.stdout is search("mysqld is alive")

    - name: Создание дампа базы # Необходимо для того, чтобы на replica появилась база wordpress_database
      community.docker.docker_container_exec:
        container: mysql_primary
        command: >
          mysqldump -h127.0.0.1 -uroot -p{{ mysql_root_password }} --all-databases --flush-logs
            --master-data=2 --skip-lock-tables --hex-blob 
        chdir: /
      register: mysql_dump_output

    - name: Сохранение дампа в файл
      copy:
        content: "{{ mysql_dump_output.stdout }}"
        dest: "{{ mysql_dump_path }}"

    - name: Создание пользователя для репликации MySQL
      community.mysql.mysql_user:
        login_host: 127.0.0.1
        login_port: "{{ mysql_primary_port }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "{{ repl_user }}"
        password: "{{ repl_password }}"
        host: "%"
        priv: "*.*:REPLICATION SLAVE"
        state: present

    - name: Получение текущего лог-файла и позиции
      community.mysql.mysql_replication:
        mode: getprimary
        login_host: 127.0.0.1
        login_port: "{{ mysql_primary_port }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
      register: master_status

    - name: Установка переменных для репликации
      ansible.builtin.set_fact:
        master_log_file: "{{ master_status.File }}"
        master_log_pos: "{{ master_status.Position }}"

    - name: Проверка, что репликация настроена
      ansible.builtin.assert:
        that:
          - master_log_file is defined
          - master_log_pos is defined
        fail_msg: "Не удалось получить информацию о мастер-лог-файле и позиции."

    # Создание и настройка реплики MySQL

    - name: Запуск реплика MySQL в контейнере
      community.docker.docker_container:
        name: mysql_replica
        image: mysql:5.7
        restart_policy: always
        state: started
        published_ports:
          - "{{ mysql_replica_port }}:3306"
        networks:
          - name: wp_net
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
        command: >
          --server-id=2
          --relay-log=relay-bin
          --bind-address=0.0.0.0
        volumes:
          - mysql_replica_data:/var/lib/mysql

    - name: Проверка что реплика MySQL доступна
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: "{{ mysql_replica_port }}"
        delay: 5

    - name: Ждём, пока MySQL replica внутри контейнера ответит ping
      community.docker.docker_container_exec:
        container: mysql_replica
        command: mysqladmin -h127.0.0.1 --protocol=TCP -uroot -p{{ mysql_root_password }} ping
      register: ping
      retries: 10
      delay: 3
      until: ping.stdout is search("mysqld is alive")

    - name: Передаём дамп в mysql_replica
      community.docker.docker_container_exec:
        container: mysql_replica
        command: sh -c "cat > /tmp/mysql_dump.sql"
        stdin: "{{ lookup('file', mysql_dump_path) }}"

    # Импортируем дамп для того чтобы появилась база wordpress_database с мастера, которая создана до начала репликации
    - name: Импортируем дамп в реплику
      community.docker.docker_container_exec:
        container: mysql_replica
        command: |
          sh -c "mysql -h127.0.0.1 --protocol=TCP -uroot -p{{ mysql_root_password }} < {{ mysql_dump_path }}"

    - name: Остановить репликацию на слейве
      community.mysql.mysql_replication:
        mode: stopreplica
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_host: 127.0.0.1   
        login_port: "{{ mysql_replica_port }}"

    - name: Настройка репликации MySQL
      community.mysql.mysql_replication:
        mode: changeprimary
        login_host: 127.0.0.1
        login_port: "{{ mysql_replica_port }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        master_host: mysql_primary
        master_port: 3306
        master_user: "{{ repl_user }}"
        master_password: "{{ repl_password }}"
        master_log_file: "{{ master_log_file }}"
        master_log_pos: "{{ master_log_pos }}"

    - name: Запуск репликации
      community.mysql.mysql_replication:
        mode: startreplica
        login_host: 127.0.0.1
        login_port: "{{ mysql_replica_port }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Проверка статуса репликации MySQL
      community.mysql.mysql_replication:
        mode: getreplica
        login_host: 127.0.0.1
        login_port: "{{ mysql_replica_port }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
      register: replica_status

    - name: Проверка успешности репликации
      ansible.builtin.assert:
        that:
          - replica_status.Slave_IO_Running == 'Yes'
          - replica_status.Slave_SQL_Running == 'Yes'
        fail_msg: "Репликация MySQL не настроена корректно {{ replica_status }}."

    - name: Создание тестовой базы данных на мастере для проверки репликации 
      community.mysql.mysql_db:
        name: "wordpress2"
        login_host: 127.0.0.1
        login_port: "{{ mysql_primary_port }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: present

    - name: Запуск WordPress в контейнере
      community.docker.docker_container:
        name: wordpress
        image: wordpress:latest
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
        networks:
          - name: wp_net
        env:
          WORDPRESS_DB_HOST: "mysql_primary:3306"
          WORDPRESS_DB_NAME: "{{ mysql_database }}"
          WORDPRESS_DB_USER: "{{ mysql_user }}"
          WORDPRESS_DB_PASSWORD: "{{ mysql_password }}"
        volumes:
          - wp_data:/var/www/html

    - name: WordPress работает корректно
      ansible.builtin.uri:
        url: "http://localhost:80"
        status_code: 200
        timeout: 10
      register: wordpress_status
      until: wordpress_status.status == 200
      retries: 10
      delay: 5
