---
- name: Установка мониторинга для MySQL-кластера
  hosts: all
  gather_facts: false
  become: true
  vars:
    mysql_root_password: root1234
    mysqld_exporter_primary_port: 9105
    mysqld_exporter_replica_port: 9106
    prometheus_port: 9091
    grafana_port: 3001
    mysql_primary_port: 3307
    mysql_replica_port: 3308
    grafana_user: admin
    grafana_password: admin

  tasks:
    - name: Получение образа mysqld-exporter
      community.docker.docker_image:
        name: prom/mysqld-exporter:latest
        source: pull

    - name: Получение образа prometheus
      community.docker.docker_image:
        name: prom/prometheus:latest
        source: pull

    - name: Получение образа grafana
      community.docker.docker_image:
        name: grafana/grafana:latest
        source: pull

    - name: Создание пользователя на Мастере MySQL # Должен реплицировать и на реплику
      community.mysql.mysql_user:
        login_host: 127.0.0.1
        login_port: "{{ mysql_primary_port }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: exporter
        password: exporter_pass
        priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
        host: "%"
        state: present

    - name: Запуск mysqld_exporter для мастера
      community.docker.docker_container:
        name: mysqld_exporter_primary
        image: prom/mysqld-exporter:latest
        restart_policy: always
        state: started
        env:
          MYSQLD_EXPORTER_PASSWORD: exporter_pass
        command: >
          --config.my-cnf=false
          --mysqld.username=exporter
          --mysqld.address="mysql_primary:3306"
        networks:
          - name: wp_net
        published_ports:
          - "{{ mysqld_exporter_primary_port }}:9104"

    - name: Проверка что mysqld_exporter_primary доступен
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: "{{ mysqld_exporter_primary_port }}"
        timeout: 60
        delay: 5

    - name: Запуск mysqld_exporter для реплики
      community.docker.docker_container:
        name: mysqld_exporter_replica
        image: prom/mysqld-exporter:latest
        restart_policy: always
        state: started
        env:
          MYSQLD_EXPORTER_PASSWORD: exporter_pass
        command: >
          --config.my-cnf=false
          --mysqld.username=exporter
          --mysqld.address="mysql_primary:3306"
        networks:
          - name: wp_net
        published_ports:
          - "{{ mysqld_exporter_replica_port }}:9104"

    - name: Проверка что mysqld_exporter_replica доступен
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: "{{ mysqld_exporter_replica_port }}"
        timeout: 60
        delay: 5

    - name: Запуск Prometheus
      community.docker.docker_container:
        name: prometheus
        image: prom/prometheus:latest
        restart_policy: always
        state: started
        volumes:
          - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
        published_ports:
          - "{{ prometheus_port }}:9090"
        networks:
          - name: wp_net

    - name: Проверка что Prometheus доступен
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: "{{ prometheus_port }}"
        timeout: 60
        delay: 5

    - name: Запуск Grafana
      community.docker.docker_container:
        name: grafana
        image: grafana/grafana:latest
        restart_policy: always
        state: started
        published_ports:
          - "{{ grafana_port }}:3000"
        volumes:
          - grafana_data:/var/lib/grafana
          - ./provisioning/datasources:/etc/grafana/provisioning/datasources
          - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
          - ./provisioning/dashboards:/var/lib/grafana/dashboards
        networks:
          - name: wp_net
        env:
          GF_SECURITY_ADMIN_USER: "{{ grafana_user }}"
          GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_password }}"
          GF_SERVER_HTTP_ADDR: "0.0.0.0"

    - name: Проверка что Grafana доступна
      ansible.builtin.uri:
        url: "http://localhost:3001/api/health"
        method: GET
        status_code: 200
      register: grafana_health
      retries: 5
      delay: 10
      until: grafana_health.status == 200

  pre_tasks:
    - name: Ожидание доступности mysql_primary
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: "{{ mysql_primary_port }}"
        timeout: 60

    - name: Ожидание доступности mysql_replica
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: "{{ mysql_replica_port }}"
        timeout: 60
